# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TmuxSessionizer < Formula
  desc "A lightweight CLI for handling TMUX sessions with ease"
  homepage "https://github.com/Pairadux/Tmux-Sessionizer"
  version "0.12.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Pairadux/Tmux-Sessionizer/releases/download/v0.12.0/Tmux-Sessionizer_Darwin_x86_64.tar.gz"
      sha256 "1532bb4f16996ac82ebb145c14282632e408ecb0cd84d451b9fc7ce90bcebe2b"

      def install
        bin.install "Tmux-Sessionizer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Pairadux/Tmux-Sessionizer/releases/download/v0.12.0/Tmux-Sessionizer_Darwin_arm64.tar.gz"
      sha256 "5a14eb20f813aa0d9743c798b310ea5181ff1565521721de1167d61637cc030a"

      def install
        bin.install "Tmux-Sessionizer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Pairadux/Tmux-Sessionizer/releases/download/v0.12.0/Tmux-Sessionizer_Linux_x86_64.tar.gz"
      sha256 "1120e003f24146e8581a039456193a34b382cdf1d32a5b1447c690f3777503e5"
      def install
        bin.install "Tmux-Sessionizer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Pairadux/Tmux-Sessionizer/releases/download/v0.12.0/Tmux-Sessionizer_Linux_arm64.tar.gz"
      sha256 "64570349c919ba1c76c0e5118f96783f9d04472cbb8d8689595d87930a43a52d"
      def install
        bin.install "Tmux-Sessionizer"
      end
    end
  end
end
