# This file was generated by GoReleaser. DO NOT EDIT.
cask "muxly" do
  name "muxly"
  desc "A lightweight CLI for handling TMUX sessions with ease"
  homepage "https://github.com/Pairadux/muxly"
  version "0.24.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "muxly"

  on_macos do
    on_intel do
      url "https://github.com/Pairadux/Muxly/releases/download/v#{version}/Muxly_Darwin_x86_64.tar.gz"
      sha256 "dd4283b4a01710c0c0bce6e7b14244688db51d6b04b42717767bfa9e2983096f"
    end
    on_arm do
      url "https://github.com/Pairadux/Muxly/releases/download/v#{version}/Muxly_Darwin_arm64.tar.gz"
      sha256 "5376c2a4105a173c18c515704252dd063b4c2b7957996451455738e0648f637f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Pairadux/Muxly/releases/download/v#{version}/Muxly_Linux_x86_64.tar.gz"
      sha256 "42dc710f9e1d29f2d4b4fcdb9b344a549d1bbbb2ba99d5a835803411b5e811f3"
    end
    on_arm do
      url "https://github.com/Pairadux/Muxly/releases/download/v#{version}/Muxly_Linux_arm64.tar.gz"
      sha256 "5e529b9389849df9efa7930f2e41e16cde90d1a650330a4156fe42333cdfe3de"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/muxly"]
    end
  end

  # No zap stanza required
end
