# This file was generated by GoReleaser. DO NOT EDIT.
cask "muxly" do
  name "muxly"
  desc "A lightweight CLI for handling TMUX sessions with ease"
  homepage "https://github.com/Pairadux/muxly"
  version "0.20.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "muxly"

  on_macos do
    on_intel do
      url "https://github.com/Pairadux/Muxly/releases/download/v#{version}/Muxly_Darwin_x86_64.tar.gz"
      sha256 "b664979ae04b76e91cb010dc25e48b6f292e7c65254cc68d5ad5e9a0defa648b"
    end
    on_arm do
      url "https://github.com/Pairadux/Muxly/releases/download/v#{version}/Muxly_Darwin_arm64.tar.gz"
      sha256 "10a2fca5c06cc62b8430687fa31dbf8d4480cd3ddce1f89ca49480e081e08cfd"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Pairadux/Muxly/releases/download/v#{version}/Muxly_Linux_x86_64.tar.gz"
      sha256 "3326deac631e073f80d9f3ae2ab330a86ee5b920c9cdd6f612a20f87c2283782"
    end
    on_arm do
      url "https://github.com/Pairadux/Muxly/releases/download/v#{version}/Muxly_Linux_arm64.tar.gz"
      sha256 "fc3998c5adbba91994b677211b087533ed9513cb5c94fe8c5367b682c9bacfc1"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/muxly"]
    end
  end

  # No zap stanza required
end
