# This file was generated by GoReleaser. DO NOT EDIT.
cask "muxly" do
  name "muxly"
  desc "A lightweight CLI for handling TMUX sessions with ease"
  homepage "https://github.com/Pairadux/muxly"
  version "0.15.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "muxly"

  on_macos do
    on_intel do
      url "https://github.com/Pairadux/Muxly/releases/download/v#{version}/Muxly_Darwin_x86_64.tar.gz"
      sha256 "e0e00e64e5dacc348d0d166ff4c2d2f58e173a180d99a30d616b0c26aa7673e7"
    end
    on_arm do
      url "https://github.com/Pairadux/Muxly/releases/download/v#{version}/Muxly_Darwin_arm64.tar.gz"
      sha256 "ad5d50dffc9622d37879db0ea7662faa5310b01c346dd8ea28085cd463c285b4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Pairadux/Muxly/releases/download/v#{version}/Muxly_Linux_x86_64.tar.gz"
      sha256 "e47858fb1d916b010ec5ce0b38f70046636818ae8a8eb05a8dd3c15325582297"
    end
    on_arm do
      url "https://github.com/Pairadux/Muxly/releases/download/v#{version}/Muxly_Linux_arm64.tar.gz"
      sha256 "a81dbf962128cc33f15ce84904ec9c45a9a5a8953a71bb73bef7aab80de875ed"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/muxly"]
    end
  end

  # No zap stanza required
end
