# This file was generated by GoReleaser. DO NOT EDIT.
cask "tmux-sessionizer" do
  name "tmux-sessionizer"
  desc "A lightweight CLI for handling TMUX sessions with ease"
  homepage "https://github.com/Pairadux/Tmux-Sessionizer"
  version "0.12.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tmux-sessionizer"

  on_macos do
    on_intel do
      url "https://github.com/Pairadux/Tmux-Sessionizer/releases/download/v#{version}/Tmux-Sessionizer_Darwin_x86_64.tar.gz"
      sha256 "4e0e2619f90614f985b606b095103446d64ea4aebad86d237d1971587d78a167"
    end
    on_arm do
      url "https://github.com/Pairadux/Tmux-Sessionizer/releases/download/v#{version}/Tmux-Sessionizer_Darwin_arm64.tar.gz"
      sha256 "17d23ecd63a1cb66abad15d68adc30841d3598bb9749b5b51331567ce244460b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Pairadux/Tmux-Sessionizer/releases/download/v#{version}/Tmux-Sessionizer_Linux_x86_64.tar.gz"
      sha256 "af64f9763b734e92cd5e6a5fa6afeb2b659328c91e610cee720aeff0a473f946"
    end
    on_arm do
      url "https://github.com/Pairadux/Tmux-Sessionizer/releases/download/v#{version}/Tmux-Sessionizer_Linux_arm64.tar.gz"
      sha256 "50295970581f3932e2f99e3ea8c93db1f73b8cf165cdf3d70aeda1964facf8b5"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tmux-sessionizer"]
    end
  end

  # No zap stanza required
end
