# This file was generated by GoReleaser. DO NOT EDIT.
cask "tmux-sessionizer" do
  name "tmux-sessionizer"
  desc "A lightweight CLI for handling TMUX sessions with ease"
  homepage "https://github.com/Pairadux/Tmux-Sessionizer"
  version "0.13.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tmux-sessionizer"

  on_macos do
    on_intel do
      url "https://github.com/Pairadux/Tmux-Sessionizer/releases/download/v#{version}/Tmux-Sessionizer_Darwin_x86_64.tar.gz"
      sha256 "6252416c04fac6d9892f734a3c93cf35e2f45b07a828efed0a8f01cf56deb9af"
    end
    on_arm do
      url "https://github.com/Pairadux/Tmux-Sessionizer/releases/download/v#{version}/Tmux-Sessionizer_Darwin_arm64.tar.gz"
      sha256 "9405641dfc99a1daecbdae8a9e15aadf8015b0460508c608e99322ff04d47639"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Pairadux/Tmux-Sessionizer/releases/download/v#{version}/Tmux-Sessionizer_Linux_x86_64.tar.gz"
      sha256 "89b4aa6794cf296a41bed00299da4835d88845c6b54d305918743a8178b8d558"
    end
    on_arm do
      url "https://github.com/Pairadux/Tmux-Sessionizer/releases/download/v#{version}/Tmux-Sessionizer_Linux_arm64.tar.gz"
      sha256 "5fa2cd71ddb8897bb120cdef34c27eaa7f36e03deb14c0312ffc1deca7fde252"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tmux-sessionizer"]
    end
  end

  # No zap stanza required
end
